metadata:
  last_updated: '2025-08-04 20:47:57'
  multi_label_study: multi_label_optimization_20250804_144256
  optimization_date: '2025-08-04'
  per_book_study: per_book_optimization_20250804_155419_book_Wuthering_Heights
  source_study: latest_optimization
multi_label:
  architecture:
    dropout_rate: 0.20834155152952213
    hidden_dims:
    - 407
    - 120
    - 327
    - 301
    - 301
    - 420
  training:
    batch_size: 64
    epochs: 97
    learning_rate: 0.003540373545611384
    patience: 30
    weight_decay: 2.9433622752930977e-06
per_book:
  book_Anna_Karenina:
    architecture:
      dropout_rate: 0.49840823287657215
      hidden_dims:
      - 369
      - 226
      - 339
      - 134
      - 511
      - 512
      - 201
      - 159
      - 460
    training:
      batch_size: 16
      epochs: 179
      learning_rate: 0.008384457395665736
      patience: 12
      weight_decay: 1.0886197021321246e-06
  book_Frankenstein:
    architecture:
      dropout_rate: 0.20379252853610424
      hidden_dims:
      - 226
      - 219
      - 368
      - 72
      - 81
      - 123
      - 297
      - 202
      - 196
      - 175
    training:
      batch_size: 32
      epochs: 150
      learning_rate: 0.00026928940730248414
      patience: 30
      weight_decay: 0.0008995991830688982
  book_The_Adventures_of_Alice_in_Wonderland:
    architecture:
      dropout_rate: 0.34162122009965945
      hidden_dims:
      - 193
      - 486
      - 347
      - 365
      - 474
      - 331
      - 469
      - 311
    training:
      batch_size: 16
      epochs: 65
      learning_rate: 0.000120404004542854
      patience: 17
      weight_decay: 8.307197795406656e-06
  book_Wuthering_Heights:
    architecture:
      dropout_rate: 0.22735410320706947
      hidden_dims:
      - 341
      - 335
      - 164
      - 249
      - 349
      - 504
      - 161
      - 332
      - 338
    training:
      batch_size: 16
      epochs: 139
      learning_rate: 0.0001244829035982986
      patience: 27
      weight_decay: 2.4912916349574228e-05
